addCashCount
computerbank-org-au/cbv-pos pull request #60
Opened 2021-08-09 00:20 UTC by rjobeirne

Modify the existing Float functionality to assist cash counting and reconciliation

2021-12-02 23:57 UTC, h00pl4 requested changes
Hmm, something weird going on here @rjobeirne . There seems to be a bunch of files suffixed with "~" that I don't believe should be part of this PR. Can you please review and remove these?

2021-12-03 01:12 UTC, josh-tf commented
Looks like emacs or similar text editor creating auto backup files, may need to change the local editor settings unless you think a blanket .gitignore on `*~` is better option

2021-12-03 04:05 UTC, rjobeirne commented
It's probably my editor. The trouble is I can't remember whether I used xed or Bluefish. I will investigate. I see the ~ files in my git gui (GitKraken) but I don't see them when I look in github via the browser.

2021-12-05 01:40 UTC, rjobeirne commented
Found it. Bluefish was setup to create backup files. What's the best way to delete them?

2021-12-05 02:31 UTC, josh-tf commented
Best bet would be to delete them in local copy of the pos and then put a commit for those changes

```
app/application/config/config.php~
app/application/controllers/Cashups.php~
app/application/helpers/tabular_helper.php~
app/application/language/en-US/cashups_lang.php~
app/application/models/Cashup.php~
app/application/views/cashups/form.php~
```

2021-12-05 03:39 UTC, rjobeirne commented
Backup files have been deleted as per your suggestion Josh.

2021-12-17 00:23 UTC, h00pl4 requested changes
Hey @rjobeirne , sorry for my slow reply. I'm not familiar with the functionality that you're altering. It would be good if we could have a run through of your changes over a video call, a screen recording, or even just screenshots.

2021-12-17 00:23 UTC, h00pl4 commented on app/application/config/config.php
> +$config['log_threshold'] = 1;
Was this an intentional change?

Does the fact that we had all messages being logged previously mean that we were running out of disk space, or were we coping ok? If the latter, probably makes sense to keep logging all messages.

2021-12-17 00:23 UTC, h00pl4 commented on app/application/views/cashups/form.php
> +//				echo form_dropdown('cashups_type', array(
Why are we commenting out this code? Often there is no good reason to do this. Git provides version history, so no change is ever truly lost. Better to remove unused code, rather than commenting. No guarantee that it will work as intended if we uncomment it in the future, because other changes will likely have taken place in the meantime, which could have unintended impact on the commented code.

2023-11-17 00:34 UTC, h00pl4 commented
Hey @rjobeirne, does this change still have merit? If so, can I please request that you add screenshots or screen recordings showing before and after the change, to help me review it?

2023-11-17 01:16 UTC, rjobeirne commented
I wouldn't bother proceeding. Ray and I use a spreadsheet on the front desk computer but we are the only ones. Every one else seems to do it the manual way. Also I'm not sure it is even possible to execute within ospos.

2023-12-12 09:52 UTC, closed without merging