add text saying that computers can be paid for using PayPal
computerbank-org-au/cbv-pos pull request #63
Opened 2021-11-28 06:55 UTC by junlinz2

2021-12-03 00:03 UTC, h00pl4 commented on app/application/views/partial/header.php
> -	<script src="bower_components/html2canvas/build/html2canvas.js"></script>
Hey @junlinz2 , can I ask why we're removing this script?

2021-12-03 01:09 UTC, josh-tf commented
Hmm that's strange that its even included in the first place, `html2canvas` isn't used anywhere in the original codebase or our fork and unless it was used as part of their development in the past I don't know where taking a page screenshot would be used

2022-01-14 01:33 UTC, h00pl4 commented on app/application/views/partial/header.php
> -	<script src="bower_components/html2canvas/build/html2canvas.js"></script>
Hey @junlinz2 , just following up on this. Any ideas?

2022-01-14 04:28 UTC, junlinz2 commented on app/application/views/partial/header.php
> -	<script src="bower_components/html2canvas/build/html2canvas.js"></script>
hey @h00pl4 , sorry I've been away. Very sure I didn't explicitly remove this line, but will take a look at this issue later.

2022-01-27 02:12 UTC, junlinz2 commented on app/application/views/partial/header.php
> -	<script src="bower_components/html2canvas/build/html2canvas.js"></script>
Hey @h00pl4 , just added it back directly on github

2022-01-28 00:26 UTC, h00pl4 requested changes

2022-01-28 00:26 UTC, h00pl4 commented on app/application/views/partial/header.php
> -	<script src="bower_components/html2canvas/build/html2canvas.js"></script>
Hey @junlinz2 , seeing some formatting changes now. I'd suggest, if you didn't intend to touch this file, revert it to master version, then we'll do a Squash commit, so that there's no history of you changing it.

2022-01-30 02:21 UTC, merged